# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rgb2dvi_0_0/Arty_Z7_20_rgb2dvi_0_0.xci
# IP: The module: 'Arty_Z7_20_rgb2dvi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rgb2dvi_0_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_20_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_20_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_20_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rgb2dvi_0_0/Arty_Z7_20_rgb2dvi_0_0.xci
# IP: The module: 'Arty_Z7_20_rgb2dvi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rgb2dvi_0_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_20_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_20_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_20_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
