# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/sam_work/git/digilent/Arty-Z7-20-base/proj/Arty_Z7_20.cache/wt [current_project]
set_property parent.project_path C:/sam_work/git/digilent/Arty-Z7-20-base/proj/Arty_Z7_20.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths C:/sam_work/git/digilent/vivado-boards/new/board_files [current_project]
set_property board_part digilentinc.com:arty-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths c:/sam_work/git/digilent/Arty-Z7-20-base/repo [current_project]
set_property ip_output_repo c:/sam_work/git/digilent/Arty-Z7-20-base/repo/cache [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/hdl/Arty_Z7_20_wrapper.vhd
add_files C:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/Arty_Z7_20.bd
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_hdmi_0/Arty_Z7_20_axi_gpio_hdmi_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_hdmi_0/Arty_Z7_20_axi_gpio_hdmi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_hdmi_0/Arty_Z7_20_axi_gpio_hdmi_0.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_led_0/Arty_Z7_20_axi_gpio_led_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_led_0/Arty_Z7_20_axi_gpio_led_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_led_0/Arty_Z7_20_axi_gpio_led_0.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_shield_1_0/Arty_Z7_20_axi_gpio_shield_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_shield_1_0/Arty_Z7_20_axi_gpio_shield_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_shield_1_0/Arty_Z7_20_axi_gpio_shield_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_shield_2_0/Arty_Z7_20_axi_gpio_shield_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_shield_2_0/Arty_Z7_20_axi_gpio_shield_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_shield_2_0/Arty_Z7_20_axi_gpio_shield_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_sw_0/Arty_Z7_20_axi_gpio_sw_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_sw_0/Arty_Z7_20_axi_gpio_sw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_sw_0/Arty_Z7_20_axi_gpio_sw_0.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_vdma_0_0/Arty_Z7_20_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_vdma_0_0/Arty_Z7_20_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_vdma_0_0/Arty_Z7_20_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axis_subset_converter_0_0/Arty_Z7_20_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_processing_system7_0_0/Arty_Z7_20_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_xbar_0/Arty_Z7_20_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rst_processing_system7_0_100M_0/Arty_Z7_20_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rst_processing_system7_0_100M_0/Arty_Z7_20_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rst_processing_system7_0_100M_0/Arty_Z7_20_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rst_processing_system7_0_142M_0/Arty_Z7_20_rst_processing_system7_0_142M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rst_processing_system7_0_142M_0/Arty_Z7_20_rst_processing_system7_0_142M_0.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rst_processing_system7_0_142M_0/Arty_Z7_20_rst_processing_system7_0_142M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_v_axi4s_vid_out_0_0/Arty_Z7_20_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_v_axi4s_vid_out_0_0/Arty_Z7_20_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_v_tc_0_0/Arty_Z7_20_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_v_tc_0_0/Arty_Z7_20_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_xadc_wiz_0_0/Arty_Z7_20_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_xadc_wiz_0_0/Arty_Z7_20_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_0/Arty_Z7_20_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_0/Arty_Z7_20_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_0/Arty_Z7_20_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_1/Arty_Z7_20_proc_sys_reset_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_1/Arty_Z7_20_proc_sys_reset_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_1/Arty_Z7_20_proc_sys_reset_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_clk_wiz_0_0/Arty_Z7_20_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_clk_wiz_0_0/Arty_Z7_20_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_clk_wiz_0_0/Arty_Z7_20_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_2/Arty_Z7_20_proc_sys_reset_0_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_2/Arty_Z7_20_proc_sys_reset_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_2/Arty_Z7_20_proc_sys_reset_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_s00_regslice_0/Arty_Z7_20_s00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_s00_data_fifo_0/Arty_Z7_20_s00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_auto_pc_0/Arty_Z7_20_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_auto_pc_1/Arty_Z7_20_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/Arty_Z7_20_ooc.xdc]
set_property is_locked true [get_files C:/sam_work/git/digilent/Arty-Z7-20-base/src/bd/Arty_Z7_20/Arty_Z7_20.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/sam_work/git/digilent/Arty-Z7-20-base/src/constraints/ARTY_Z7.xdc
set_property used_in_implementation false [get_files C:/sam_work/git/digilent/Arty-Z7-20-base/src/constraints/ARTY_Z7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Arty_Z7_20_wrapper -part xc7z020clg400-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


write_checkpoint -force -noxdef Arty_Z7_20_wrapper.dcp

catch { report_utilization -file Arty_Z7_20_wrapper_utilization_synth.rpt -pb Arty_Z7_20_wrapper_utilization_synth.pb }
